import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import StickyLinkedIn from "@/components/StickyLinkedIn";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "ProfilePage",
              "mainEntity": {
                "@type": "Person",
                "name": "Saptarshi",
                "jobTitle": [
                  "Brand Manager",
                  "Content Strategist",
                  "Social Media Manager",
                  "Social Media Executive",
                  "Brand Associate",
                  "MarCom Specialist",
                  "Media Content Coordinator"
                ],
                "description": "Marketing Content End-to-End Execution Specialist specializing in high-retention social media marketing and brand growth infrastructure.",
                "knowsAbout": [
                  "Social Media Marketing",
                  "Brand Management",
                  "Content Strategy",
                  "MarCom Operations",
                  "Organic Audience Architecture"
                ]
              }
            })
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <StickyLinkedIn />
      </body>
    </html>
  );
}
