import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import StickyLinkedIn from "@/components/StickyLinkedIn";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@graph": [
                {
                  "@type": "ProfilePage",
                  "@id": "https://www.saptarshi.cv/#profilepage",
                  "url": "https://www.saptarshi.cv",
                  "mainEntity": {
                    "@id": "https://www.saptarshi.cv/#person"
                  }
                },
                {
                  "@type": "Person",
                  "@id": "https://www.saptarshi.cv/#person",
                  "name": "Saptarshi",
                  "jobTitle": [
                    "Marketing Content End-to-End Execution Specialist",
                    "Brand Manager",
                    "Content Strategist",
                    "Social Media Manager",
                    "Social Media Executive",
                    "Brand Associate",
                    "MarCom Specialist",
                    "Media Content Coordinator"
                  ],
                  "description": "Marketing Content End-to-End Execution Specialist orchestrating 5.2M+ organic views for national brands by bridging consumer behavioral psychology with high-velocity in-house production control.",
                  "knowsAbout": [
                    "Social Media Marketing",
                    "Brand Management",
                    "Content Strategy",
                    "MarCom Operations",
                    "Organic Audience Architecture",
                    "Consumer Behavioral Psychology",
                    "Open-Source Web Architecture Development"
                  ],
                  "address": {
                    "@type": "PostalAddress",
                    "addressLocality": [
                      "New Delhi",
                      "Kolkata",
                      "Mumbai",
                      "Bangalore"
                    ],
                    "addressRegion": "India"
                  },
                  "sameAs": [
                    "https://www.linkedin.com/in/saptarshi-dutta-storytelling/",
                    "https://github.com/lapaasindia/website-builder"
                  ]
                }
              ]
            })
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <StickyLinkedIn />
      </body>
    </html>
  );
}
